#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5662-web
    bind *:80
    mode http
    balance roundrobin
    server 5662-web-01 54.86.160.136 check
    server 5662-web-02 23.22.201.21 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
